name: challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  bloc: ^8.1.4
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  stacked_card_carousel: ^0.0.4
  flutter_swipe_action_cell: ^3.1.3
  fluttertoast: ^8.2.6
  auto_route: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.1.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  bloc_test: ^9.1.7
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/