name: challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverbloc: ^2.1.0
  hooks_riverpod: ^2.3.0
  flutter_hooks: ^0.18.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  google_fonts: ^5.1.0
  stacked_card_carousel: ^0.0.4
  flutter_swipe_action_cell: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  freezed: ^2.3.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/